### ISSUE TITLE
Separate by category?

### ISSUE THREAD

**Issue by sdhull** [jedireza/reserved-subdomains#1]
This is really handy but I was wondering what you thought about separating out the "external companies" into a different list. I'm not sure I care much if someone creates `riteaid.myapp.com` but I definitely don't want them creating `admin.myapp.com` or `login.myapp.com`.

Right now I'm deleting everything I can find that is external-company related from the list. Would you be interested in a pull request that separates these?

**Comment by jedireza** [comment]
> Would you be interested in a pull request that separates these?

Yeah that might be good for maintenance purposes. Though I haven't touched this repo since I created it. If things work the same by default, I'm open to reviewing a PR. 👍 

> I'm not sure I care much if someone creates `riteaid.myapp.com` but I definitely don't want them creating `admin.myapp.com` or `login.myapp.com`.

While it doesn't hit every company name, this is nice to prevent some obvious DMCA takedown requests for large brands. While you don't care that a user creates `mcdonalds.yourapp.com`, you'll be in line when legal comes knocking.

If you really want to drop certain sets, it may be best to just take a copy and repurpose it into a custom solution for your app.
